services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/sonarr:/config
      - ${TV}:/tv
      - ${DOWNLOADS}:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/bazarr:/config
      - ${MOVIES}:/movies
      - ${TV}:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/overseerr:/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  overseerr-kids:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr-kids
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/overseerr-kids:/config
    ports:
      - "5056:5055"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/sabnzbd:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - "8080:8080"
    restart: unless-stopped

  radarr-kids:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-kids
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/radarr-kids:/config
      - ${MOVIES_KIDS}:/movies
      - ${DOWNLOADS}:/downloads
    ports:
      - "7879:7878"
    restart: unless-stopped

  sonarr-kids:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-kids
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/sonarr-kids:/config
      - ${TV_KIDS}:/tv
      - ${DOWNLOADS}:/downloads
    ports:
      - "8990:8989"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/plex:/config
      - ${MOVIES}:/data/movies
      - ${TV}:/data/tv
      - ${MOVIES_KIDS}:/data/kids-movies
      - ${TV_KIDS}:/data/kids-tv
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /opt/arr/lidarr:/config
      - ${MUSIC}:/music
      - ${DOWNLOADS}:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped
