services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/radarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/bazarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tv:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/overseerr:/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  overseerr-kids:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr-kids
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/overseerr-kids:/config
    ports:
      - "5056:5055"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/sabnzbd:/config
      - /mnt/media/downloads:/downloads
    ports:
      - "8080:8080"
    restart: unless-stopped

  radarr-kids:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-kids
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/radarr-kids:/config
      - /mnt/media/movies-kids:/movies
      - /mnt/media/downloads:/downloads
    ports:
      - "7879:7878"
    restart: unless-stopped

  sonarr-kids:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-kids
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/sonarr-kids:/config
      - /mnt/media/tv-kids:/tv
      - /mnt/media/downloads:/downloads
    ports:
      - "8990:8989"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/plex:/config
      - /mnt/media/movies:/data/movies
      - /mnt/media/tv:/data/tv
      - /mnt/media/movies-kids:/data/kids-movies
      - /mnt/media/tv-kids:/data/kids-tv
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=Asia/Dubai
    volumes:
      - /opt/arr/lidarr:/config
      - /mnt/media/music:/music
      - /mnt/media/downloads:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped
